### ISSUE TITLE
Write replay server

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-rs#112]
The server replays a previous session reading and synchronising the trajectory (#19) and the shared state (#111).

**Comment by jbarnoud** [comment]
@rhoslynroebuck What do you think should happen when we reach the end of the recording by default?

From the top of my head, the options are:
* stop at the last frame
* loop

I would probably go for stopping at the last frame but maybe you have another scenario in mind.

**Comment by rhoslynroebuck** [comment]
Stopping at the last frame seems sensible. The looping can be implemented by the python client.
